---
title: "Lab 06"
author: "Daniel de Souza Gama (266805)"
format: pdf
editor: visual
---

```{r}
library(DBI)
library(RSQLite)
```

# 1)

```{r}
path <- "."
fname <- file.path(path, "disco.db")
```

# 2)

```{r}
conn <- dbConnect(RSQLite::SQLite(), fname)
```

# 3)

```{r}
dbListTables(conn)
```

# 4)

```{r}
dbListFields(conn, "Customer")
```

# 5)

```{r}
dbGetQuery(conn, 
  "SELECT COUNT (*) AS Total_Clientes 
  FROM Customer"
  )
```

# 6)

```{r}
dbGetQuery(conn, 
  "SELECT COUNT(DISTINCT Country) AS Total_Paises 
  FROM Customer"
)
```

# 7)

```{r}
dbGetQuery(conn, 
  "SELECT Country, COUNT(*) AS Quantidade_Clientes
  FROM Customer
  GROUP BY Country
  ORDER BY Quantidade_Clientes DESC"
)
```

# 8)

```{r}
dbGetQuery(conn, 
  "SELECT Country, COUNT(*) AS Quantidade_Clientes
  FROM Customer
  GROUP BY Country
  ORDER BY Quantidade_Clientes DESC
  LIMIT 5"
)
```

# 9)

```{r}
dbGetQuery(conn,
  "SELECT DISTINCT Country
  FROM Customer
  WHERE LENGTH(Country) = 6"
)
```

# 10)

```{r}
dbGetQuery(conn, 
  "SELECT DISTINCT t.Name AS Nome_Musica
  FROM Customer c
  JOIN Invoice i ON c.CustomerId = i.CustomerId
  JOIN InvoiceLine il ON i.InvoiceId = il.InvoiceId
  JOIN Track t ON il.TrackId = t.TrackId
  WHERE c.Country = 'Brazil'"
)
```

# 11)

```{r}
dbDisconnect(conn)
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
