---
title: "Lista 06"
author: "Daniel de Souza Gama"
format: pdf
editor: visual
---

```{r}

library(DBI)
library(RSQLite)
con<- dbConnect(RSQLite::SQLite(),'me315.sqlite')
```

# 1)

```{sql connection=con}
SELECT STATE, MIN(ACRES) FROM PRESERVE 
GROUP BY STATE
```

# 2)

```{sql connection=con}
SELECT STATE, MAX(ACRES) FROM PRESERVE 
WHERE ACRES <= 10000 
GROUP BY STATE
```

# 3)

```{sql connection=con}
SELECT STATE, MAX(ACRES) FROM PRESERVE 
WHERE ACRES <= 10000 
GROUP BY STATE 
ORDER BY MAX(ACRES) DESC
```

# 4)

```{sql connection=con}
SELECT STATE, MAX(ACRES) FROM PRESERVE 
GROUP BY STATE 
HAVING MAX(ACRES) < 25000
```

# 5)

```{sql connection=con}
SELECT STATE, MIN(ACRES) FROM PRESERVE 
GROUP BY STATE 
HAVING MIN(ACRES) < 100
```

# 6)

```{sql connection=con}
SELECT STATE, PNAME, MAX(ACRES) FROM PRESERVE 
WHERE ACRES > 1000 
GROUP BY STATE 
HAVING MAX(ACRES) < 25000
```

# 7)

```{sql connection=con}
SELECT STATE, SUM(ACRES) FROM PRESERVE 
GROUP BY STATE 
HAVING SUM(ACRES) BETWEEN 10000 AND 50000
```

# 8)

```{sql connection=con}
SELECT MAX(MediaAcres) FROM (
    SELECT AVG(ACRES) AS MediaAcres 
    FROM PRESERVE 
    GROUP BY STATE)
```

# 9)

```{sql connection=con}
SELECT DNO, AVG(SALARY) FROM EMPLOYEE 
GROUP BY DNO
```

# 10)

```{sql connection=con}
SELECT DNO, SUM(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEE 
GROUP BY DNO
```

# 11)

```{sql connection=con}
SELECT DNO, COUNT() FROM EMPLOYEE 
WHERE DNO <> 40 
GROUP BY DNO
```

# 12)

```{sql connection=con}
SELECT DNO, COUNT() FROM EMPLOYEE 
GROUP BY DNO 
HAVING COUNT() > 2
```

# 13)

```{sql connection=con}
SELECT STATE, SUM(ACRES) AS "SUM (ACRES)" FROM PRESERVE 
GROUP BY STATE
UNION ALL
SELECT 'Total', SUM(ACRES) FROM PRESERVE
```

```{r}
Sys.setenv(TZ = "America/Sao_Paulo")
Sys.time()
```
